version: "3.7"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      servers:
      browsers:
    volumes:
      - levels:/mnt/levels
      - level0:/mnt/level0
      - level1:/mnt/level1
      - level2:/mnt/level2
      - level3:/mnt/level3
      - level4:/mnt/level4
      - level5:/mnt/level5
      - level6:/mnt/level6
      - level7:/mnt/level7
      - level8:/mnt/level8
  level0:
    build:
      context: ./levels/0
    networks:
      servers:
        aliases:
          - level0-stripe-ctf
    environment:
      - PWPATH=/mnt/level0/password.txt
    volumes:
      - level0:/mnt/level0
  level1:
    build:
      context: ./levels/1
    networks:
      servers:
        aliases:
          - level1-stripe-ctf
    environment:
      - PWPATH=/mnt/level1/password.txt
    volumes:
      - level1:/mnt/level1
  level2:
    build:
      context: ./levels/2
    networks:
      servers:
        aliases:
          - level2-stripe-ctf
    environment:
      - PWPATH=/mnt/level2/password.txt
    volumes:
      - level2:/mnt/level2
  level3:
    build:
      context: ./levels/3
    networks:
      servers:
        aliases:
          - level3-stripe-ctf
    environment:
      - LEVEL3_DATA_DIR=/var/level3/data
      - PWPATH=/mnt/level3/password.txt
    volumes:
      - level3:/mnt/level3
  level4-server:
    build:
      context: ./levels/4/server
    command: serve
    networks:
      servers:
        aliases:
          - level4-stripe-ctf
      browsers:
    environment:
      - PW_FILE=/mnt/level4/password.txt
    volumes:
      - level4:/mnt/level4
  level4-browser:
    build:
      context: ./levels/4/browser
    cap_add:
      - SYS_ADMIN
    environment:
      - PW_FILE=/mnt/level4/password.txt
    volumes:
      - level4:/mnt/level4
    networks:
      - browsers
  level5:
    build:
      context: ./levels/5
    command: serve
    depends_on:
      - level2
    networks:
      servers:
        aliases:
          - level5-stripe-ctf
    environment:
      - PW_FILE=/mnt/level5/password.txt
    volumes:
      - level5:/mnt/level5
  level6-server:
    build:
      context: ./levels/6/server
    command: serve
    networks:
      servers:
        aliases:
          - level6-stripe-ctf
      browsers:
    environment:
      - PW_FILE=/mnt/level6/password.txt
    volumes:
      - level6:/mnt/level6
  level6-browser:
    build:
      context: ./levels/6/browser
    cap_add:
      - SYS_ADMIN
    environment:
      - PW_FILE=/mnt/level6/password.txt
    volumes:
      - level6:/mnt/level6
    networks:
      - browsers
  level7:
    build:
      context: ./levels/7
    command: serve
    networks:
      servers:
        aliases:
          - level7-stripe-ctf
    environment:
      - PW_FILE=/mnt/level7/password.txt
    volumes:
      - level7:/mnt/level7
  level8:
    build:
      context: ./levels/8
    depends_on:
      - level2
    networks:
      servers:
        aliases:
          - level8-stripe-ctf
    environment:
      - PW_FILE=/mnt/level8/password.txt
    volumes:
      - level8:/mnt/level8
volumes:
  passwords:
  levels:
  level0:
  level1:
  level2:
  level3:
  level4:
  level5:
  level6:
  level7:
  level8:
networks:
  browsers:
    driver: bridge
    internal: true
  servers:
    driver: bridge
