version: "3.7"
services:
  ctfproxy:
    init: true
    build: ./ctfproxy
    image: gcr.io/stripe-ctf-demo/ctfproxy
    ports:
      - "8000:8000"
    depends_on:
      - level0
      - level1
      - level2
      - level3
      - level4-server
      - level5
      - level6-server
      - level7
      - level8
