version: "3.7"
services:
  level0:
    init: true
    build:
      context: ./levels/0
    image: gcr.io/stripe-ctf-demo/level0
    env_file:
      - ./env/0.env
  level1:
    build:
      context: ./levels/1
    image: gcr.io/stripe-ctf-demo/level1
  level2:
    build:
      context: ./levels/2
    image: gcr.io/stripe-ctf-demo/level2
  level3:
    build:
      context: ./levels/3
    image: gcr.io/stripe-ctf-demo/level3
  level4-server:
    build:
      context: ./levels/4/server
    image: gcr.io/stripe-ctf-demo/level4-server
  level4-browser:
    build:
      context: ./levels/4/browser
    image: gcr.io/stripe-ctf-demo/level4-browser
    depends_on:
      - level4-server
  level5:
    build:
      context: ./levels/5
    image: gcr.io/stripe-ctf-demo/level5
    depends_on:
      - level2
  level6-server:
    build:
      context: ./levels/6/server
    image: gcr.io/stripe-ctf-demo/level6-server
  level6-browser:
    build:
      context: ./levels/6/browser
    image: gcr.io/stripe-ctf-demo/level6-browser
    depends_on:
      - level6-server
  level7:
    build:
      context: ./levels/7
    image: gcr.io/stripe-ctf-demo/level7
  level8:
    build:
      context: ./levels/8
    image: gcr.io/stripe-ctf-demo/level8
    depends_on:
      - level2
networks:
  browsers:
    driver: bridge
  levels:
    driver: bridge
