version: "3.7"
services:
  ctfproxy-frontend:
    build:
      context: ./ctfproxy
      target: node
    volumes:
      - ./ctfproxy:/usr/src/app
      - /usr/src/app/node_modules
    command: npmwatch
  ctfproxy-server:
    build:
      context: ./ctfproxy
      target: go
    volumes:
      - ./ctfproxy:/usr/src/app
      - ./levels:/usr/src/levels
    command: gowatch
    environment:
      - LEVELCODE=/usr/src/levels
      - STATIC_DIR=/usr/src/app/static
      - LEVEL0_INTERNAL_URL=http://level0:3000
      - LEVEL0_EXTERNAL_URL=http://level0.stripe-ctf.com:8000
      - LEVEL1_INTERNAL_URL=http://level1:8000
      - LEVEL1_EXTERNAL_URL=http://level1.stripe-ctf.com:8000
      - LEVEL2_INTERNAL_URL=http://level2:8000
      - LEVEL2_EXTERNAL_URL=http://level2.stripe-ctf.com:8000
      - LEVEL3_INTERNAL_URL=http://level3:5000
      - LEVEL3_EXTERNAL_URL=http://level3.stripe-ctf.com:8000
      - LEVEL4_INTERNAL_URL=http://level4-server:4567
      - LEVEL4_EXTERNAL_URL=http://level4.stripe-ctf.com:8000
      - LEVEL5_INTERNAL_URL=http://level5:4567
      - LEVEL5_EXTERNAL_URL=http://level5.stripe-ctf.com:8000
      - LEVEL6_INTERNAL_URL=http://level6-server:4567
      - LEVEL6_EXTERNAL_URL=http://level6.stripe-ctf.com:8000
      - LEVEL7_INTERNAL_URL=http://level7:9233
      - LEVEL7_EXTERNAL_URL=http://level7.stripe-ctf.com:8000
      - LEVEL8_INTERNAL_URL=http://level8:4000
      - LEVEL8_EXTERNAL_URL=http://level8.stripe-ctf.com:8000
      - CTFPROXY_EXTERNAL_URL=http://stripe-ctf.com:8000
      - STATIC_URL=/static
    env_file:
      - ./env/ctfproxy.env
    ports:
      - "8000:8000"
    networks:
      proxy:
      levels:
  cron:
    init: true
    build:
      context: ./cron
    networks:
      - browsers
  level0:
    volumes:
      - ./levels/0:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      levels:
        aliases:
          - level0-stripe-ctf
  level1:
    init: true
    volumes:
      - ./levels/1:/usr/src/app
    networks:
      levels:
        aliases:
          - level1-stripe-ctf
    env_file:
      - ./env/1.env
  level2:
    init: true
    volumes:
      - ./levels/2:/usr/src/app
    networks:
      browsers:
        aliases:
          - level2-stripe-ctf
      levels:
        aliases:
          - level2-stripe-ctf
    env_file:
      - ./env/2.env
  level3:
    init: true
    volumes:
      - ./levels/3:/usr/src/app
    networks:
      levels:
        aliases:
          - level3-stripe-ctf
    environment:
      - DATA_DIR=/var/level3/data
    env_file:
      - ./env/3.env
  level4-browser:
    init: true
    volumes:
      - ./levels/4/browser:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - browsers
    env_file:
      - ./env/4.env
    environment:
      - URL=http://level4-server:4567
  level4-server:
    init: true
    volumes:
      - ./levels/4/server:/usr/src/app
    networks:
      levels:
        aliases:
          - level4-stripe-ctf
      browsers:
    environment:
      - DB_FILE=/usr/src/app/karma.db
    env_file:
      - ./env/4.env
  level6-browser:
    init: true
    volumes:
      - ./levels/6/browser:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - browsers
    env_file:
      - ./env/6.env
    environment:
      - URL=http://level6-server:4567
  level5:
    init: true
    volumes:
      - ./levels/5:/usr/src/app
    networks:
      levels:
        aliases:
          - level5-stripe-ctf
    env_file:
      - ./env/5.env
    command: serve
  level6-server:
    init: true
    volumes:
      - ./levels/6/server:/usr/src/app
    networks:
      levels:
        aliases:
          - level6-stripe-ctf
      browsers:
    env_file:
      - ./env/6.env
  level7:
    init: true
    volumes:
      - ./levels/7:/usr/src/app
    networks:
      levels:
        aliases:
          - level7-stripe-ctf
    env_file:
      - ./env/7.env
  level8:
    init: true
    volumes:
      - ./levels/8:/usr/src/app
    networks:
      levels:
        aliases:
          - level8-stripe-ctf
    env_file:
      - ./env/8.env

networks:
  browsers:
    driver: bridge
  levels:
    driver: bridge
  proxy:
    driver: bridge
