steps:
# build the container image
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/level7:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=8h
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'level7'
  - '--image'
  - 'gcr.io/$PROJECT_ID/level7:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
