steps:
# build the container image
- name: 'gcr.io/kaniko-project/executor:v0.20.0'
  args:
  - '--destination=gcr.io/$PROJECT_ID/ctfproxy:$COMMIT_SHA'
  - '--cache=true'
  - '--cache-ttl=8h'
# Copy static files to volume
- name: 'gcr.io/$PROJECT_ID/ctfproxy:$COMMIT_SHA'
  volumes:
  - name: 'static'
    path: '/mnt/static'
  args:
  - 'cp'
  - '-v'
  - '-R'
  - '/usr/src/app/static/'
  - '/mnt/static/'
# List static files for debugging
- name: 'gcr.io/$PROJECT_ID/ctfproxy:$COMMIT_SHA'
  volumes:
  - name: 'static'
    path: '/mnt/static'
  args:
  - 'ls'
  - '/mnt/static/'
# Copy static files to cloud storage
- name: 'gcr.io/cloud-builders/gsutil'
  volumes:
  - name: 'static'
    path: '/mnt/static'
  args:
  - '-m'
  - 'rsync'
  - '-r'
  - '-c'
  - '-d'
  - '/mnt/static/'
  - 'gs://ctfproxy-static/'
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'ctfproxy'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ctfproxy:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
